# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'TestNaviBar' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'DeviceKit', '~> 2.0'

  pod 'AutoInch'
  pod 'SnapKit'

end
