# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestPay' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestPay
  pod 'SwiftyStoreKit',  '0.14.2'

  target 'TestPayTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
