# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestRealm' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestRealm
  pod 'Realm',                      '3.14.2'
  pod 'RealmSwift',                 '3.14.2'

  target 'TestRealmTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
