# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TestCollection' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TestCollection
  pod 'MagazineLayout',   :source => 'https://git.dev.tencent.com/hanshoujun/ZeroPrivateRepository.git'
  pod 'XLPagerTabStrip',            '8.1.1'

  target 'TestCollectionTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
